"""Materialize served exemplar images from data/exemplars/manifest.yaml.

For every manifest entry: resolve the source (repo-local `local_path`, else
download `source_url`), verify its pinned sha256, then write the SERVED
derivatives into the frontend build tree:

  frontend/public/exemplars/<id>.jpg         (max side 1024px, JPEG q85)
  frontend/public/exemplars/thumbs/<id>.jpg  (max side 320px, JPEG q80)

These ship with the site build — no separate S3 sync path. A hard total-size
budget keeps the build lean; the script fails loudly if the budget is blown.

Usage (repo root):  python scripts/fetch_exemplars.py [--check-only]
"""
from __future__ import annotations

import argparse
import hashlib
import urllib.request
from io import BytesIO
from pathlib import Path

import yaml
from PIL import Image

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = REPO_ROOT / "data" / "exemplars" / "manifest.yaml"
ATTRIBUTION_DOC = REPO_ROOT / "docs" / "exemplar-attribution.md"
OUT_FULL = REPO_ROOT / "frontend" / "public" / "exemplars"
OUT_THUMB = OUT_FULL / "thumbs"
MAX_TOTAL_BYTES = 25 * 1024 * 1024
FULL_SIDE, THUMB_SIDE = 1024, 320
ALLOWED_LICENSES = {"public_domain", "cc0", "cc_by"}
UA = "DefectLensExemplars/1.0 (research; github keysmon/multimodal-defect-inspection)"


def load_manifest() -> list[dict]:
    data = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    entries = data["exemplars"]
    ids = [e["id"] for e in entries]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate exemplar ids in manifest")
    return entries


def source_bytes(entry: dict) -> bytes:
    local = entry.get("local_path")
    if local:
        path = REPO_ROOT / local
        if not path.exists():
            raise SystemExit(
                f"{entry['id']}: {local} missing — run the dataset fetch/prepare "
                "scripts in docs/datasets.md first"
            )
        data = path.read_bytes()
    else:
        req = urllib.request.Request(entry["source_url"], headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = resp.read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != entry["sha256"]:
        raise SystemExit(
            f"{entry['id']}: sha256 mismatch (got {digest[:12]}..., "
            f"manifest pins {entry['sha256'][:12]}...)"
        )
    return data


def write_resized(data: bytes, dest: Path, max_side: int, quality: int) -> int:
    with Image.open(BytesIO(data)) as im:
        im = im.convert("RGB")
        im.thumbnail((max_side, max_side))
        dest.parent.mkdir(parents=True, exist_ok=True)
        buf = BytesIO()
        im.save(buf, "JPEG", quality=quality)
    dest.write_bytes(buf.getvalue())
    return len(buf.getvalue())


def write_attribution(entries: list[dict]) -> None:
    """Regenerate docs/exemplar-attribution.md from the manifest (no drift)."""
    lines = [
        "# Exemplar image attribution",
        "",
        "AUTO-GENERATED by `scripts/fetch_exemplars.py` from",
        "`data/exemplars/manifest.yaml` — edit the manifest, not this file.",
        "",
        "Served exemplars are restricted to public-domain, CC0, and CC BY",
        "sources; per-image license checks are recorded in the manifest's",
        "`license_check` field.",
        "",
        "| id | license | credit | source |",
        "|---|---|---|---|",
    ]
    for e in entries:
        lines.append(
            f"| {e['id']} | {e['license']} | {e['credit']} | {e['source_url']} |"
        )
    ATTRIBUTION_DOC.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check-only", action="store_true",
        help="verify sources + hashes without writing derivatives",
    )
    args = parser.parse_args()

    entries = load_manifest()
    total = 0
    for entry in entries:
        if entry["license"] not in ALLOWED_LICENSES:
            raise SystemExit(f"{entry['id']}: license {entry['license']!r} not allowed")
        data = source_bytes(entry)
        if args.check_only:
            continue
        total += write_resized(data, OUT_FULL / f"{entry['id']}.jpg", FULL_SIDE, 85)
        total += write_resized(data, OUT_THUMB / f"{entry['id']}.jpg", THUMB_SIDE, 80)
    if args.check_only:
        print(f"OK: {len(entries)} entries verified (hashes + licenses)")
        return
    if total > MAX_TOTAL_BYTES:
        raise SystemExit(
            f"exemplar build weighs {total / 1e6:.1f} MB > "
            f"{MAX_TOTAL_BYTES / 1e6:.0f} MB budget — trim entries or quality"
        )
    write_attribution(entries)
    print(f"OK: {len(entries)} exemplars -> {OUT_FULL} ({total / 1e6:.1f} MB)")
    print(f"attribution doc -> {ATTRIBUTION_DOC}")


if __name__ == "__main__":
    main()
