"""Package the fine-tuned VLM adapter into a SageMaker model.tar.gz (Phase 5.5c).

The GPU async endpoint (infra/stacks/gpu_stack.py) serves the fine-tuned
Qwen2.5-VL classifier on the HuggingFace PyTorch Inference DLC. That DLC expects
a model.tar.gz laid out as:

    adapter_config.json            <- LoRA adapter (SageMaker's model_dir root)
    adapter_model.safetensors
    code/inference.py              <- the handler (SAGEMAKER_SUBMIT_DIRECTORY)
    code/requirements.txt          <- extra pip deps installed at endpoint start

The ~8GB Qwen2.5-VL-3B BASE weights are intentionally NOT in the tarball — they
download from the HuggingFace hub inside inference.model_fn at endpoint start, so
this artifact stays ~120MB (the adapter) and the first cold start pays a ~5-8 min
base-download tax. Baking the base in would make an 8GB+ tarball for no benefit.

Usage (models/ is gitignored, so the adapter must exist locally first):

    python scripts/package_sagemaker_model.py --out dist/model.tar.gz
    python scripts/package_sagemaker_model.py \
        --upload-s3 s3://defectlens-phase3-ca-002559670021/phase5/sagemaker/model.tar.gz \
        --profile defectlens
"""
from __future__ import annotations

import argparse
import os
import tarfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ADAPTER_DIR = REPO_ROOT / "models" / "qwen25vl-lora-v1"
DEFAULT_CODE_DIR = REPO_ROOT / "deploy" / "sagemaker"
DEFAULT_OUT = REPO_ROOT / "dist" / "model.tar.gz"

# Handler + its deps go under code/; adapter weights/config go at the root.
CODE_FILES = ("inference.py", "requirements.txt")
# adapter_config.json + adapter_model.safetensors — the two files PeftModel needs.
# The autogenerated README.md is skipped (SageMaker never reads it).
ADAPTER_SUFFIXES = (".safetensors", ".json")


def tar_members(adapter_dir: Path, code_dir: Path) -> list[tuple[str, Path]]:
    """Planned (arcname, source_path) layout for the tarball. Pure + testable.

    Adapter weights/config land at the archive ROOT (SageMaker extracts the
    tarball to model_dir, where PeftModel.from_pretrained looks). The handler and
    its requirements land under code/. Arcnames are relative (never absolute), so
    extraction can't escape model_dir, and the base weights are absent by design.
    """
    members: list[tuple[str, Path]] = []
    for name in sorted(os.listdir(adapter_dir)):
        if name.endswith(ADAPTER_SUFFIXES):
            members.append((name, adapter_dir / name))
    for name in CODE_FILES:
        members.append((f"code/{name}", code_dir / name))
    return members


def build_tarball(out_path: Path, adapter_dir: Path, code_dir: Path) -> int:
    """Write model.tar.gz from tar_members; return its size in bytes."""
    members = tar_members(adapter_dir, code_dir)
    missing = [str(src) for _arc, src in members if not src.is_file()]
    if missing:
        raise SystemExit(
            "Cannot package — missing source file(s):\n  " + "\n  ".join(missing)
        )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(out_path, "w:gz") as tar:
        for arcname, src in members:
            tar.add(src, arcname=arcname)
    return out_path.stat().st_size


def _split_s3_uri(uri: str) -> tuple[str, str]:
    if not uri.startswith("s3://"):
        raise SystemExit(f"--upload-s3 must be an s3:// URI, got {uri!r}")
    bucket, _, key = uri[len("s3://") :].partition("/")
    if not bucket or not key:
        raise SystemExit(f"--upload-s3 must be s3://<bucket>/<key>, got {uri!r}")
    return bucket, key


def upload(out_path: Path, s3_uri: str, profile: str | None = None) -> None:
    import boto3  # lazy: keeps the module import AWS-free for the unit tests

    bucket, key = _split_s3_uri(s3_uri)
    session = boto3.Session(profile_name=profile) if profile else boto3.Session()
    session.client("s3").upload_file(str(out_path), bucket, key)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--adapter-dir", type=Path, default=DEFAULT_ADAPTER_DIR)
    parser.add_argument("--code-dir", type=Path, default=DEFAULT_CODE_DIR)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--upload-s3", type=str, default=None, help="s3://bucket/key to upload the tarball to"
    )
    parser.add_argument(
        "--profile", type=str, default=None, help="AWS profile for the upload (e.g. defectlens)"
    )
    args = parser.parse_args()

    size = build_tarball(args.out, args.adapter_dir, args.code_dir)
    print(f"Wrote {args.out} ({size / 1e6:.1f} MB)")
    for arcname, _src in tar_members(args.adapter_dir, args.code_dir):
        print(f"  {arcname}")

    if args.upload_s3:
        upload(args.out, args.upload_s3, profile=args.profile)
        print(f"Uploaded to {args.upload_s3}")


if __name__ == "__main__":
    main()
